# Generated by Django 5.1.1 on 2024-09-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
