# Generated by Django 5.1.1 on 2024-09-25 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city_order_email_order_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 20, 57, 56, 916501, tzinfo=datetime.timezone.utc)),
        ),
    ]
