# Generated by Django 5.1.1 on 2024-09-28 23:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_cart_alter_cartitem_quantity'),
        ('orders', '0014_order_cart_alter_orderinfo_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 23, 3, 55, 40698, tzinfo=datetime.timezone.utc)),
        ),
    ]
