# Generated by Django 5.1.1 on 2024-09-28 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_cart_alter_orderinfo_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 23, 32, 21, 248573, tzinfo=datetime.timezone.utc)),
        ),
    ]
