# Generated by Django 5.1.1 on 2024-09-30 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderinfo_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
