# Generated by Django 5.1.1 on 2024-09-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=2, upload_to='category'),
            preserve_default=False,
        ),
    ]
